title: Best-Category Ever Template Discussion
labels: ["bug", "good first question"]
body:
  - type: markdown
    attributes:
       value: |
         If you post this it will live on the internet FOREVER!
  - type: textarea
    attributes:
      label: What's on your mind? 
  - type: textarea
    attributes:
      label: What is your social security number?
