title: Discussion Template for Favorite Things
body:
  - type: textarea
    attributes:
      label: Color
  - type: textarea
    attributes:
      label: Food
  - type: textarea
    attributes:
      label: Song
  - type: textarea
    attributes:
      label: Movie
  - type: textarea
    attributes:
      label: Season
  - type: textarea
    attributes:
      label: Holiday
