name: Hello
labels: ["Help"]
body:
  - type: markdown
    attributes:
      value: |
        The more specific you can be, the easier it will be to help you!
  - type: textarea
    attributes:
      label: Describe your issue
  - type: textarea
    attributes:
      label: Are you using third party plugins? If yes, list them here.
  - type: dropdown
    attributes:
      label: Which version are you running?
      options:
        - 1
        - 2
        - 3
