labels: ["Help"]
body:
  - type: markdown
    attributes:
      value: |
        The more specific you can be, the easier it will be to help you!
  - type: textarea
    attributes:
      label: Describe your issue
  - type: textarea
    attributes:
      label: Are you using third party plugins? If yes, list them here.
  - type: dropdown
    attributes:
      label: Which version are you running?
      options:
        - 1
        - 2
        - 3
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
          - OS:
          - Node:
          - npm:
      render: markdown
    validations:
      required: false
