title: <h1>The title</h1>
labels: ["bold"]
body:
  - type: markdown
    attributes:
      value: |
        <h3>If you post this it will live on the internet FOREVER !!!!!</h3>
  - type: textarea
    attributes:
      label: What's on your mind? 
